#!/usr/bin/env python3
"""Render the sector-regime-heatmap scores into this repo's README.

The heatmap scores the 11 GICS sectors from the price panel this repo commits,
so its output belongs on this front page too. The forecast artifact is read
from a sibling checkout -- the same relationship in the other direction as
`stage_run.py --panel ../weekly-council-scan/data/weekly`.

Nothing is invented. If the sibling checkout is absent, or it has published no
forecast, the block says exactly that. A grid of placeholder scores on a front
page is worse than an empty one, because it looks authoritative.

    python scripts/render_heatmap_dashboard.py
    python scripts/render_heatmap_dashboard.py --heatmap ../sector-regime-heatmap
    python scripts/render_heatmap_dashboard.py --check    # fails if stale

ASCII only, per CLAUDE.md. The chart then renders the same in a terminal, a
diff and a browser.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
README = ROOT / "README.md"
START = ("<!-- HEATMAP:START - generated by "
         "scripts/render_heatmap_dashboard.py, do not edit -->")
END = "<!-- HEATMAP:END -->"

DEFAULT_HEATMAP = ROOT.parent / "sector-regime-heatmap"
REPO_URL = "https://github.com/GrandMastaShake/sector-regime-heatmap"

BAR_CELLS = 10
SHORT_RATING = {"favorable": "fav", "constructive": "con", "neutral": "neu",
                "unfavorable": "unf", "defensive": "def",
                "unavailable": "n/a"}


def bar(score) -> str:
    """A 10-cell gauge. A horizon that was not offered is dots, never zero."""
    if score is None:
        return "[" + "." * BAR_CELLS + "]"
    filled = int(round(max(0.0, min(100.0, float(score))) / 100 * BAR_CELLS))
    return "[" + "#" * filled + "-" * (BAR_CELLS - filled) + "]"


def latest_forecast(heatmap_root: Path):
    """(doc, relative_path) for the newest forecast, or (None, reason)."""
    if not heatmap_root.is_dir():
        return None, ("no checkout of sector-regime-heatmap at `"
                      + str(heatmap_root) + "`")
    d = heatmap_root / "data" / "forecasts"
    if not d.is_dir():
        return None, "the heatmap checkout has no `data/forecasts/` directory"
    files = [p for p in sorted(d.glob("*.json")) if p.is_file()]
    if not files:
        return None, "the heatmap has published no forecast yet"
    best = max(files, key=lambda p: (
        json.loads(p.read_text(encoding="utf-8"))["as_of_date"], p.name))
    return json.loads(best.read_text(encoding="utf-8")), "data/forecasts/" + best.name


def sort_key(item):
    _sector, row = item
    s = row["week"]["score"]
    return (0 if s is None else 1, s if s is not None else 0)


def render_chart(scores: dict) -> list:
    rows = sorted(scores.items(), key=sort_key, reverse=True)
    width = max(len(s) for s, _ in rows)
    lines = ["```",
             "sector".ljust(width) + "   week                    month",
             "-" * (width + 48)]
    for sector, row in rows:
        parts = []
        for horizon in ("week", "month"):
            score = row[horizon]["score"]
            shown = "  n/a" if score is None else ("%5.1f" % score)
            rating = SHORT_RATING.get(row[horizon]["rating"], "?")
            parts.append(shown + " " + rating + " " + bar(score))
        lines.append(sector.ljust(width) + "   " + "   ".join(parts))
    lines.append("```")
    return lines


def build(heatmap_root: Path) -> str:
    lines = [START, "", "## Sector Regime Heatmap", ""]
    doc, detail = latest_forecast(heatmap_root)

    if doc is None:
        lines += [
            "**No forecast to show** -- " + detail + ".",
            "",
            "The heatmap scores the 11 GICS sectors from the weekly price panel this",
            "repo commits. Nothing is rendered here rather than showing placeholder",
            "scores. See [" + REPO_URL.split("/")[-1] + "](" + REPO_URL + ").",
            "", END,
        ]
        return "\n".join(lines)

    regime = doc["regime"]
    against = regime.get("disconfirming_evidence") or []
    lines += [
        "Scored from the weekly price panel in this repo by",
        "[sector-regime-heatmap](" + REPO_URL + ").",
        "",
        "**As of " + doc["as_of_date"] + "** -- " + doc["run_type"] + " run  ",
        "**Regime:** " + regime["label"] + "  ",
        "**Confidence:** " + regime["confidence"] + " -- "
        + str(len(regime.get("evidence") or [])) + " supporting, "
        + str(len(against)) + " disconfirming",
        "",
    ]
    lines += render_chart(doc["scores"])
    lines += [
        "",
        "`fav` 70+, `con` 55+, `neu` 45+, `unf` 30+, `def` below 30. `n/a` is a",
        "horizon that was not offered -- the day horizon needs daily bars and this",
        "feed commits Friday closes only -- never a zero.",
        "",
        "Full rationale, per-sector sourcing and the disconfirming evidence are in",
        "the heatmap's own README and in `" + detail + "` there.",
        "", END,
    ]
    return "\n".join(lines)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Render the heatmap dashboard block.")
    ap.add_argument("--heatmap", type=Path, default=DEFAULT_HEATMAP,
                    help="path to the sector-regime-heatmap checkout "
                         "(default: sibling of this repo)")
    ap.add_argument("--readme", type=Path, default=README)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the block is stale instead of writing")
    args = ap.parse_args(argv)

    text = args.readme.read_text(encoding="utf-8")
    if START not in text or END not in text:
        print("README.md has no HEATMAP markers; add them where the block "
              "should live:")
        print(START)
        print(END)
        return 1

    head = text[: text.index(START)]
    tail = text[text.index(END) + len(END):]
    updated = head + build(args.heatmap) + tail

    if args.check:
        if updated != text:
            print("README heatmap block is stale. Run: "
                  "python scripts/render_heatmap_dashboard.py")
            return 1
        print("README heatmap block is up to date.")
        return 0

    args.readme.write_text(updated, encoding="utf-8", newline="\n")
    print("Updated the README heatmap block.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
